export default interface FormControlProps {
    name: string;
    label?: string | JSX.Element;
    labelPosition?: 'top' | 'column';
    className?: string;
    placeholder?: string;
    type?: string;
    ref?: any;
    id?: string;
    as?: 'input' | 'textarea' | React.ElementType;
    disabled?: boolean;
    htmlSize?: number;
    isInvalid?: boolean;
    isValid?: boolean;
    onChange?: (e: any) => void;
    plaintext?: boolean;
    readOnly?: boolean;
    value?: string | any[] | number;
    controlId: string;
    htmlFor?: string;
    bsPrefix?: string;
    size?: 'sm' | 'lg';
    ariaDescribedby?: string;
    ariaLabel?: string;
    caption?: string;
    captionId?: string;
    hasValidation?: boolean;
    appendControl?: (props: { [key: string]: any }) => JSX.Element;
    prependControl?: (props: { [key: string]: any }) => JSX.Element;
    tabIndex?: number;
}